brain_two/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("todos/", include("todos.urls")),
]

todos/urls.py
from django.urls import path
from todos.views import todo_list_list, todo_list_detail, todo_list_create

app_name = "todos"

urlpatterns = [
    path("", todo_list_list, name="todo_list_list"),
    path("<int:id>/", todo_list_detail, name="todo_list_detail"),
    path("create/", todo_list_create, name="todo_list_create"),
]

todos/models.py
from django.db import models

# Create your models here.


class TodoList(models.Model):
    name = models.CharField(max_length=100)
    created_on = models.DateTimeField(auto_now_add=True)


class TodoItem(models.Model):
    task = models.CharField(max_length=100)
    due_date = models.DateTimeField(null=True, blank=True)
    is_completed = models.BooleanField(default=False)
    list = models.ForeignKey(
        TodoList, on_delete=models.CASCADE, related_name="items",
    )

    def __str__(self):
        return self.task

todos/forms.py
from django import forms
from django.forms import ModelForm
from .models import TodoList


class TodoListForm(ModelForm):
    class Meta:
        model = TodoList
        fields = ["name"]

todos/views.py
from django.shortcuts import render, get_object_or_404, redirect
from todos.models import TodoList
from todos.forms import TodoListForm

# Create your views here.


def todo_list_list(request):
    todo_lists = TodoList.objects.all()
    context = {"todo_lists": todo_lists}
    return render(request, "todos/todo_list_list.html", context)


def todo_list_detail(request, id):
    list = TodoList.objects.get(id=id)
    context = {"list": list}
    return render(request, "todos/todo_list_detail.html", context)


def todo_list_create(request):
    if request.method == "POST":
        form = TodoListForm(request.POST)
        if form.is_valid():
            list = form.save()
            return redirect("todos:todo_list_detail", id=list.id)
    else:
        form = TodoListForm()

    context = {
        "form": form,
    }
    return render(request, "todos/todo_list_create.html", context)

todos/templates/todos/todo_list_create.html
<!Doctype html>
<html>
    <head>
        <body>
            <div>
                <h1>Create a new list</h1>
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Create</button>
                  </form>
            </div>
        </body>
    </head>
</html>

todos/templates/todos/todo_list_detail.html
<!DOCTYPE html>
<html>
    <head>
        <body>
            <main>
                <div>
                    <h1>{{ list.name }}</h1>
                    <h2>Task</h2>
                    <table>
                        <thead>
                            <tr>
                                <th>Task</th>
                                <th>Due date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for todo_item in todo_list.items.all %}
                            <tr>
                                <td>{{ item.task }}</td>
                                <td>{{ item.due_date|date:"F j, Y" }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </main>
        </body>
    </head>
</html>

todos/templates/todos/todo_list_list.html
<!Doctype html>
<html>
    <head>
        <body>
            <main>
                <div>
                    <h1>My Lists</h1>
                    <p>
                        <a href="{% url 'todos:todo_list_create' %}">Create a new list</a>
                    </p>
                    <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Number of items</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for todo_list in todo_lists %}
                                <tr>
                                    <td><a href="{% url 'todos:todo_list_detail' id=todo_list.id %}">{{ todo_list.name }}</a></td>
                                    <td>{{ todo_list.items.count }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </main>
        </body>
    </head>
</html>